import type { Product } from '~/types/product'

export const products: Product[] = [
  {
    id: 1,
    name: 'Laptop Reconditionné EcoBook Pro',
    description: 'Laptop reconditionné haute performance, certifié écologique.',
    longDescription: 'Le EcoBook Pro est un laptop soigneusement reconditionné avec des composants vérifiés et une batterie neuve. Idéal pour les professionnels soucieux de l\'environnement. Chaque unité est testée rigoureusement et livrée avec une garantie 2 ans.',
    price: 649.99,
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&q=80',
    category: 'Ordinateurs',
    stock: 12,
    rating: 4.7,
    reviewCount: 243,
    specs: {
      'Processeur': 'Intel Core i7 (10ème gen)',
      'RAM': '16 Go DDR4',
      'Stockage': '512 Go SSD',
      'Écran': '15.6" Full HD',
      'Batterie': 'Neuve – jusqu\'à 10h',
      'OS': 'Windows 11 Pro',
    },
  },
  {
    id: 2,
    name: 'Clavier Mécanique GreenType',
    description: 'Clavier mécanique fabriqué à partir de plastiques recyclés.',
    longDescription: 'Le GreenType est fabriqué à 80% à partir de plastiques océaniques recyclés. Switches silencieux, rétroéclairage LED, compatible USB-C et Bluetooth. Packaging 100% sans plastique.',
    price: 89.99,
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&q=80',
    category: 'Périphériques',
    stock: 35,
    rating: 4.5,
    reviewCount: 128,
    specs: {
      'Switches': 'Mécaniques silencieux',
      'Connectivité': 'USB-C & Bluetooth 5.0',
      'Rétroéclairage': 'LED RGB',
      'Matériaux': '80% plastiques recyclés',
      'Compatibilité': 'Windows, macOS, Linux',
      'Garantie': '2 ans',
    },
  },
  {
    id: 3,
    name: 'Souris EcoGrip Wireless',
    description: 'Souris sans fil ergonomique en matériaux durables.',
    longDescription: 'La EcoGrip Wireless offre un confort ergonomique optimal avec une autonomie de 12 mois sur pile. Corps fabriqué en bioplastique issu de canne à sucre. Capteur optique précis à 4000 DPI.',
    price: 45.00,
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&q=80',
    category: 'Périphériques',
    stock: 58,
    rating: 4.3,
    reviewCount: 89,
    specs: {
      'Connectivité': '2.4 GHz sans fil',
      'DPI': '400 – 4000 DPI',
      'Autonomie': 'Jusqu\'à 12 mois',
      'Matériaux': 'Bioplastique canne à sucre',
      'Poids': '95g',
      'Garantie': '1 an',
    },
  },
  {
    id: 4,
    name: 'Écran EcoDisplay 24"',
    description: 'Écran IPS 24 pouces à faible consommation énergétique.',
    longDescription: 'L\'EcoDisplay 24" consomme 40% moins d\'énergie que les écrans conventionnels grâce à sa technologie LED avancée. Certification Energy Star et TCO Certified. Fabriqué sans substances toxiques.',
    price: 299.00,
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&q=80',
    category: 'Écrans',
    stock: 20,
    rating: 4.6,
    reviewCount: 175,
    specs: {
      'Taille': '24 pouces',
      'Résolution': '1920x1080 Full HD',
      'Panneau': 'IPS',
      'Consommation': '18W (vs 30W standard)',
      'Certifications': 'Energy Star, TCO Certified',
      'Ports': 'HDMI, DisplayPort, USB-C',
    },
  },
  {
    id: 5,
    name: 'Chargeur Solaire SunPower 65W',
    description: 'Chargeur universel alimenté par panneaux solaires intégrés.',
    longDescription: 'Le SunPower 65W est un chargeur universel qui combine un panneau solaire pliable haute efficacité avec une batterie intégrée de 20 000 mAh. Chargez vos appareils n\'importe où, sans dépendre du réseau électrique.',
    price: 129.99,
    image: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=600&q=80',
    category: 'Énergie',
    stock: 15,
    rating: 4.8,
    reviewCount: 312,
    specs: {
      'Puissance': '65W',
      'Batterie': '20 000 mAh',
      'Ports': '2x USB-A, 1x USB-C PD',
      'Panneau': 'Silicium monocristallin 23%',
      'Poids': '480g',
      'Garantie': '3 ans',
    },
  },
  {
    id: 6,
    name: 'Hub USB-C EcoConnect 7 en 1',
    description: 'Hub multiports fabriqué en aluminium recyclé.',
    longDescription: 'L\'EcoConnect est un hub USB-C 7 en 1 fabriqué en aluminium recyclé à 95%. Compatible avec tous les laptops USB-C, il offre 4K HDMI, 3x USB-A 3.0, SD/microSD, et USB-C 100W PD. Design compact et durable.',
    price: 59.99,
    image: 'https://images.unsplash.com/photo-1616578273461-3a99ce422de6?q=80&w=1364&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    category: 'Accessoires',
    stock: 42,
    rating: 4.4,
    reviewCount: 207,
    specs: {
      'Ports': '3x USB-A 3.0, HDMI 4K, USB-C PD 100W, SD, microSD',
      'Matériaux': 'Aluminium recyclé 95%',
      'Compatibilité': 'Tous laptops USB-C',
      'Résolution HDMI': '4K @30Hz',
      'Vitesse USB': '5 Gbps',
      'Garantie': '2 ans',
    },
  },
  {
    id: 7,
    name: 'Casque Audio BioSound Pro',
    description: 'Casque audio sans fil fabriqué en bois certifié FSC.',
    longDescription: 'Le BioSound Pro allie qualité sonore audiophile et éco-responsabilité. Les pavillons sont en bois de noyer certifié FSC, les mousses des coussinets en latex naturel. Autonomie de 30h, recharge rapide USB-C.',
    price: 179.99,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80',
    category: 'Audio',
    stock: 8,
    rating: 4.9,
    reviewCount: 94,
    specs: {
      'Connectivité': 'Bluetooth 5.2',
      'Autonomie': '30 heures',
      'Driver': '40mm',
      'Matériaux': 'Bois FSC, latex naturel',
      'Recharge': 'USB-C rapide (10min = 3h)',
      'Garantie': '2 ans',
    },
  },
  {
    id: 8,
    name: 'Tablette RecycTab 10"',
    description: 'Tablette Android reconditionnée, comme neuve.',
    longDescription: 'La RecycTab est une tablette reconditionnée de 10 pouces avec écran Full HD, chipset performant et batterie renouvelée. Chaque tablette est livrée avec Android 13, testée pendant 72h et couverte par une garantie 18 mois.',
    price: 189.00,
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&q=80',
    category: 'Tablettes',
    stock: 18,
    rating: 4.2,
    reviewCount: 156,
    specs: {
      'Écran': '10.1" Full HD IPS',
      'Processeur': 'Octa-core 2.0 GHz',
      'RAM': '4 Go',
      'Stockage': '64 Go + microSD',
      'OS': 'Android 13',
      'Batterie': '7040 mAh (neuve)',
    },
  },
]

export const categories = [...new Set(products.map(p => p.category))]
